In [1]:
!pip install numpy

In [2]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
arr2=np.array([1,2,3,4])
arr2.reshape(1,4)

array([[1, 2, 3, 4]])

In [8]:
arr2=np.array([[1,2,3,4,5],[4,5,6,7,8]])

In [9]:
print(arr2)

[[1 2 3 4 5]
 [4 5 6 7 8]]


In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr1=np.array([1,2,3,4])
arr2=np.array([4,5,6,7])

print("addition" , arr1 + arr2)

addition [ 5  7  9 11]


In [14]:
print(np.sqrt(arr1))

[1.         1.41421356 1.73205081 2.        ]


In [16]:
print(np.sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [17]:
arr2=np.array([[1,2,3,4,5],[4,5,6,7,8]])

In [23]:
arr2[0:,1:]

array([[2, 3, 4, 5],
       [5, 6, 7, 8]])